[2023-09-01T06:16:42.530+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bash_test.task1 manual__2023-09-01T06:16:41.166356+00:00 [queued]>
[2023-09-01T06:16:42.545+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bash_test.task1 manual__2023-09-01T06:16:41.166356+00:00 [queued]>
[2023-09-01T06:16:42.547+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-09-01T06:16:42.566+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): task1> on 2023-09-01 06:16:41.166356+00:00
[2023-09-01T06:16:42.574+0000] {standard_task_runner.py:57} INFO - Started process 5580 to run task
[2023-09-01T06:16:42.581+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'bash_test', 'task1', 'manual__2023-09-01T06:16:41.166356+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/test_dags2.py', '--cfg-path', '/tmp/tmprhh_74m_']
[2023-09-01T06:16:42.586+0000] {standard_task_runner.py:85} INFO - Job 42: Subtask task1
[2023-09-01T06:16:42.655+0000] {task_command.py:415} INFO - Running <TaskInstance: bash_test.task1 manual__2023-09-01T06:16:41.166356+00:00 [running]> on host 8ef33824b8b6
[2023-09-01T06:16:42.770+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bash_test' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2023-09-01T06:16:41.166356+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-01T06:16:41.166356+00:00'
[2023-09-01T06:16:42.778+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-09-01T06:16:42.780+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python module/crawling.py -site hankook -c politics']
[2023-09-01T06:16:42.798+0000] {subprocess.py:86} INFO - Output:
[2023-09-01T06:16:42.933+0000] {subprocess.py:93} INFO - python: can't open file 'module/crawling.py': [Errno 2] No such file or directory
[2023-09-01T06:16:42.938+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-09-01T06:16:42.953+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-09-01T06:16:42.962+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=bash_test, task_id=task1, execution_date=20230901T061641, start_date=20230901T061642, end_date=20230901T061642
[2023-09-01T06:16:42.982+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 42 for task task1 (Bash command failed. The command returned a non-zero exit code 2.; 5580)
[2023-09-01T06:16:43.037+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-01T06:16:43.067+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
