[2023-09-01T06:17:14.378+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bash_test.task1 manual__2023-09-01T06:17:13.216771+00:00 [queued]>
[2023-09-01T06:17:14.393+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bash_test.task1 manual__2023-09-01T06:17:13.216771+00:00 [queued]>
[2023-09-01T06:17:14.395+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-09-01T06:17:14.414+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): task1> on 2023-09-01 06:17:13.216771+00:00
[2023-09-01T06:17:14.422+0000] {standard_task_runner.py:57} INFO - Started process 5881 to run task
[2023-09-01T06:17:14.428+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'bash_test', 'task1', 'manual__2023-09-01T06:17:13.216771+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/test_dags2.py', '--cfg-path', '/tmp/tmpfgbbr1l7']
[2023-09-01T06:17:14.434+0000] {standard_task_runner.py:85} INFO - Job 43: Subtask task1
[2023-09-01T06:17:14.514+0000] {task_command.py:415} INFO - Running <TaskInstance: bash_test.task1 manual__2023-09-01T06:17:13.216771+00:00 [running]> on host 8ef33824b8b6
[2023-09-01T06:17:14.641+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bash_test' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2023-09-01T06:17:13.216771+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-01T06:17:13.216771+00:00'
[2023-09-01T06:17:14.645+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-09-01T06:17:14.647+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'pwd && python module/crawling.py -site hankook -c politics']
[2023-09-01T06:17:14.666+0000] {subprocess.py:86} INFO - Output:
[2023-09-01T06:17:14.673+0000] {subprocess.py:93} INFO - /tmp/***tmpzq0zp7tp
[2023-09-01T06:17:14.827+0000] {subprocess.py:93} INFO - python: can't open file 'module/crawling.py': [Errno 2] No such file or directory
[2023-09-01T06:17:14.833+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-09-01T06:17:14.851+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-09-01T06:17:14.859+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=bash_test, task_id=task1, execution_date=20230901T061713, start_date=20230901T061714, end_date=20230901T061714
[2023-09-01T06:17:14.878+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 43 for task task1 (Bash command failed. The command returned a non-zero exit code 2.; 5881)
[2023-09-01T06:17:14.924+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-01T06:17:14.949+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
