[2023-09-01T06:52:33.422+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bash_test.sports scheduled__2023-08-31T06:52:00+00:00 [queued]>
[2023-09-01T06:52:33.557+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bash_test.sports scheduled__2023-08-31T06:52:00+00:00 [queued]>
[2023-09-01T06:52:33.561+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-09-01T06:52:33.649+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): sports> on 2023-08-31 06:52:00+00:00
[2023-09-01T06:52:33.694+0000] {standard_task_runner.py:57} INFO - Started process 24179 to run task
[2023-09-01T06:52:33.730+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'bash_test', 'sports', 'scheduled__2023-08-31T06:52:00+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/test_dags2.py', '--cfg-path', '/tmp/tmpe7_pjcs2']
[2023-09-01T06:52:33.735+0000] {standard_task_runner.py:85} INFO - Job 60: Subtask sports
[2023-09-01T06:52:34.164+0000] {task_command.py:415} INFO - Running <TaskInstance: bash_test.sports scheduled__2023-08-31T06:52:00+00:00 [running]> on host 8ef33824b8b6
[2023-09-01T06:52:34.505+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bash_test' AIRFLOW_CTX_TASK_ID='sports' AIRFLOW_CTX_EXECUTION_DATE='2023-08-31T06:52:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-31T06:52:00+00:00'
[2023-09-01T06:52:34.509+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-09-01T06:52:34.512+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/ && python src/crawling.py -s hankook -c sports -d 20230831']
[2023-09-01T06:52:34.544+0000] {subprocess.py:86} INFO - Output:
[2023-09-01T06:54:45.616+0000] {subprocess.py:93} INFO - Sports ['HG01', 'HG02', 'HG03', 'HG04', 'HG05', 'HG06', 'HG99'] 20230831
[2023-09-01T06:54:53.299+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-09-01T06:54:53.566+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 1155, in _create_direct_connection
[2023-09-01T06:54:53.818+0000] {subprocess.py:93} INFO -     hosts = await asyncio.shield(host_resolved)
[2023-09-01T06:54:53.955+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 874, in _resolve_host
[2023-09-01T06:54:54.080+0000] {subprocess.py:93} INFO -     addrs = await self._resolver.resolve(host, port, family=self._family)
[2023-09-01T06:54:54.114+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/aiohttp/resolver.py", line 33, in resolve
[2023-09-01T06:54:54.137+0000] {subprocess.py:93} INFO -     infos = await self._loop.getaddrinfo(
[2023-09-01T06:54:54.177+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/asyncio/base_events.py", line 825, in getaddrinfo
[2023-09-01T06:54:54.200+0000] {subprocess.py:93} INFO -     return await self.run_in_executor(
[2023-09-01T06:54:54.277+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
[2023-09-01T06:54:55.176+0000] {subprocess.py:93} INFO -     result = self.fn(*self.args, **self.kwargs)
[2023-09-01T06:54:55.202+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
[2023-09-01T06:54:55.300+0000] {subprocess.py:93} INFO -     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
[2023-09-01T06:54:55.555+0000] {subprocess.py:93} INFO - socket.gaierror: [Errno -3] Temporary failure in name resolution
[2023-09-01T06:54:55.556+0000] {subprocess.py:93} INFO - 
[2023-09-01T06:54:55.597+0000] {subprocess.py:93} INFO - The above exception was the direct cause of the following exception:
[2023-09-01T06:54:55.629+0000] {subprocess.py:93} INFO - 
[2023-09-01T06:54:55.708+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-09-01T06:54:55.834+0000] {subprocess.py:93} INFO -   File "src/crawling.py", line 135, in <module>
[2023-09-01T06:54:55.840+0000] {subprocess.py:93} INFO -     main()
[2023-09-01T06:54:55.861+0000] {subprocess.py:93} INFO -   File "src/crawling.py", line 126, in main
[2023-09-01T06:54:55.865+0000] {subprocess.py:93} INFO -     loop.run_until_complete(run(site, main_category, sub_category, date))
[2023-09-01T06:54:55.868+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
[2023-09-01T06:54:55.871+0000] {subprocess.py:93} INFO -     return future.result()
[2023-09-01T06:54:55.876+0000] {subprocess.py:93} INFO -   File "src/crawling.py", line 92, in run
[2023-09-01T06:54:55.885+0000] {subprocess.py:93} INFO -     await asyncio.gather(*futures)
[2023-09-01T06:54:55.893+0000] {subprocess.py:93} INFO -   File "src/crawling.py", line 69, in get_news
[2023-09-01T06:54:55.928+0000] {subprocess.py:93} INFO -     async for html in detail_html:
[2023-09-01T06:54:55.943+0000] {subprocess.py:93} INFO -   File "src/crawling.py", line 66, in <genexpr>
[2023-09-01T06:54:55.947+0000] {subprocess.py:93} INFO -     detail_html = (await get_html(url) for url in news_detail_urls)
[2023-09-01T06:54:55.963+0000] {subprocess.py:93} INFO -   File "src/crawling.py", line 32, in get_html
[2023-09-01T06:54:55.966+0000] {subprocess.py:93} INFO -     async with session.get(url, headers={'User-Agent':'Mozilla/5.0'}) as resp:
[2023-09-01T06:54:55.972+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/aiohttp/client.py", line 1141, in __aenter__
[2023-09-01T06:54:55.999+0000] {subprocess.py:93} INFO -     self._resp = await self._coro
[2023-09-01T06:54:56.020+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/aiohttp/client.py", line 536, in _request
[2023-09-01T06:54:56.022+0000] {subprocess.py:93} INFO -     conn = await self._connector.connect(
[2023-09-01T06:54:56.035+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 540, in connect
[2023-09-01T06:54:56.040+0000] {subprocess.py:93} INFO -     proto = await self._create_connection(req, traces, timeout)
[2023-09-01T06:54:56.050+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 901, in _create_connection
[2023-09-01T06:54:56.057+0000] {subprocess.py:93} INFO -     _, proto = await self._create_direct_connection(req, traces, timeout)
[2023-09-01T06:54:56.066+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 1169, in _create_direct_connection
[2023-09-01T06:54:56.078+0000] {subprocess.py:93} INFO -     raise ClientConnectorError(req.connection_key, exc) from exc
[2023-09-01T06:54:56.098+0000] {subprocess.py:93} INFO - aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host www.hankookilbo.com:443 ssl:default [Temporary failure in name resolution]
[2023-09-01T06:54:57.685+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-09-01T06:54:57.752+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-09-01T06:54:57.860+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=bash_test, task_id=sports, execution_date=20230831T065200, start_date=20230901T065233, end_date=20230901T065457
[2023-09-01T06:54:57.963+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 60 for task sports (Bash command failed. The command returned a non-zero exit code 1.; 24179)
[2023-09-01T06:54:58.330+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-01T06:54:59.010+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
