[2023-09-01T06:21:07.783+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bash_test.task1 manual__2023-09-01T06:21:06.649275+00:00 [queued]>
[2023-09-01T06:21:07.799+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bash_test.task1 manual__2023-09-01T06:21:06.649275+00:00 [queued]>
[2023-09-01T06:21:07.801+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-09-01T06:21:07.822+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): task1> on 2023-09-01 06:21:06.649275+00:00
[2023-09-01T06:21:07.832+0000] {standard_task_runner.py:57} INFO - Started process 8148 to run task
[2023-09-01T06:21:07.838+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'bash_test', 'task1', 'manual__2023-09-01T06:21:06.649275+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/test_dags2.py', '--cfg-path', '/tmp/tmpt6s9xjo5']
[2023-09-01T06:21:07.841+0000] {standard_task_runner.py:85} INFO - Job 46: Subtask task1
[2023-09-01T06:21:07.944+0000] {task_command.py:415} INFO - Running <TaskInstance: bash_test.task1 manual__2023-09-01T06:21:06.649275+00:00 [running]> on host 8ef33824b8b6
[2023-09-01T06:21:08.130+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bash_test' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2023-09-01T06:21:06.649275+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-01T06:21:06.649275+00:00'
[2023-09-01T06:21:08.139+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-09-01T06:21:08.145+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/ && python src/crawling.py -s hankook -c politics']
[2023-09-01T06:21:08.168+0000] {subprocess.py:86} INFO - Output:
[2023-09-01T06:21:13.780+0000] {subprocess.py:93} INFO - Politics
[2023-09-01T06:21:13.782+0000] {subprocess.py:93} INFO - ['HA01', 'HA02', 'HA03', 'HA04', 'HA99']
[2023-09-01T06:21:13.785+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-09-01T06:21:13.789+0000] {subprocess.py:93} INFO -   File "src/crawling.py", line 131, in <module>
[2023-09-01T06:21:13.790+0000] {subprocess.py:93} INFO -     main()
[2023-09-01T06:21:13.792+0000] {subprocess.py:93} INFO -   File "src/crawling.py", line 122, in main
[2023-09-01T06:21:13.794+0000] {subprocess.py:93} INFO -     loop.run_until_complete(run(site, main_category, sub_category, today))
[2023-09-01T06:21:13.795+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
[2023-09-01T06:21:13.797+0000] {subprocess.py:93} INFO -     return future.result()
[2023-09-01T06:21:13.799+0000] {subprocess.py:93} INFO -   File "src/crawling.py", line 90, in run
[2023-09-01T06:21:13.801+0000] {subprocess.py:93} INFO -     await asyncio.gather(*futures)
[2023-09-01T06:21:13.801+0000] {subprocess.py:93} INFO -   File "src/crawling.py", line 85, in get_news
[2023-09-01T06:21:13.803+0000] {subprocess.py:93} INFO -     await save(news)
[2023-09-01T06:21:13.804+0000] {subprocess.py:93} INFO -   File "src/crawling.py", line 25, in save
[2023-09-01T06:21:13.805+0000] {subprocess.py:93} INFO -     db.insert_bulk(q=sql, arg=values)
[2023-09-01T06:21:13.807+0000] {subprocess.py:93} INFO - NameError: name 'db' is not defined
[2023-09-01T06:21:14.014+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-09-01T06:21:14.035+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-09-01T06:21:14.044+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=bash_test, task_id=task1, execution_date=20230901T062106, start_date=20230901T062107, end_date=20230901T062114
[2023-09-01T06:21:14.065+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 46 for task task1 (Bash command failed. The command returned a non-zero exit code 1.; 8148)
[2023-09-01T06:21:14.110+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-01T06:21:14.135+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
